function renderAll(){renderOverview();renderProducts();renderBatches();renderBatchSuggestions();renderSettings();renderInvestments();renderShoppingSimulation()}
function renderOverview(){const ps=state.products,cs=ps.map(calcProduct);$('#kpiProducts').textContent=ps.length;$('#kpiBatches').textContent=state.batches.length;$('#kpiReady').textContent=ps.filter(p=>p.status==='ready').length+' verkaufsbereit';$('#kpiAvgPrice').textContent=euro(ps.length?cs.reduce((a,c)=>a+c.recommended,0)/ps.length:0);$('#kpiAvgMargin').textContent=pct(ps.length?cs.reduce((a,c)=>a+c.margin,0)/ps.length:0);const s=state.settings;$('#feeRateSummary').textContent=(s.transactionPct+s.paymentPct).toFixed(2).replace('.',',')+' %';$('#feeFixedSummary').textContent=euro(s.listingFee+s.paymentFixed);$('#feeAdsSummary').textContent=s.offsitePct.toFixed(2).replace('.',',')+' %';$('#feeFxSummary').textContent=s.currencyPct.toFixed(2).replace('.',',')+' %';const el=$('#overviewProducts');if(!ps.length){el.innerHTML='<div class="empty"><strong>Noch keine Produkte</strong>Lege dein erstes Produkt an.<br><button class="btn primary" style="margin-top:10px" onclick="openProduct()">+ Produkt</button></div>';return}el.innerHTML='<div class="table-wrap"><table><thead><tr><th>ID</th><th>Produkt</th><th>Status</th><th>Kosten</th><th>VK</th><th>Marge</th></tr></thead><tbody>'+ps.slice(-6).reverse().map(p=>{const c=calcProduct(p);return `<tr style="cursor:pointer" onclick="openProduct('${p.key}')"><td><span class="idchip">${esc(p.pid)}</span></td><td><div class="name">${esc(p.name)}</div>${productColorDots(p.colors,true)}</td><td><span class="badge ${p.status}">${statusLabel(p.status)}</span></td><td class="money">${euro(c.costs)}</td><td class="money">${euro(p.salePrice)}</td><td>${pct(c.margin)}</td></tr>`}).join('')+'</tbody></table></div>'}
function renderSettings(){const s=state.settings;['listingFee','transactionPct','paymentPct','paymentFixed','offsitePct','currencyPct','feeVatPct','setupFee','setupSales'].forEach(k=>{const e=$('#'+k);if(e&&document.activeElement!==e)e.value=s[k]});$('#setupPerSale').textContent=euro(s.setupSales>0?s.setupFee/s.setupSales:0)}
$$('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.go)));function switchTab(t){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$$('.tabpage').forEach(p=>p.classList.add('hidden'));$('#tab-'+t).classList.remove('hidden')}
initColorFilter();$('#addProductBtn').onclick=()=>openProduct();$('#addBatchBtn').onclick=()=>openBatch();$('#searchProducts').oninput=renderProducts;$('#filterProductColor').onchange=renderProducts;$('#searchBatches').oninput=renderBatches;const refreshSuggestions=$('#refreshBatchSuggestionsBtn');if(refreshSuggestions)refreshSuggestions.onclick=renderBatchSuggestions;
$('#addSupplierBtn').onclick=()=>{const has=$$('.supplier-row').length;$('#supplierRows').insertAdjacentHTML('beforeend',supplierRowHtml({id:crypto.randomUUID(),name:'',url:'',priceType:'unit',price:0,minOrderQty:1,setPrice:0,setQty:1,totalShipping:0,imageUrl:'',customs:false,preferred:!has}));bindSupplierEvents();liveCalc()};
$('#usePreferredPriceBtn').onclick=()=>{const s=preferredSupplier();if(s){$('#productBasePrice').value=supplierUnitPrice(s).toFixed(2);if(!$('#productImageUrl').value&&s.imageUrl){$('#productImageUrl').value=s.imageUrl;renderImagePreview(s.imageUrl)}liveCalc()}};
$('#addCostBtn').onclick=()=>{$('#costRows').insertAdjacentHTML('beforeend','<div class="cost-row"><input class="cost-name" placeholder="Kostenposition"><input class="cost-amount" type="number" min="0" step="0.01" value="0"><button type="button" class="iconbtn remove-cost">✕</button></div>');bindCostEvents();liveCalc()};
['productBasePrice','shippingCost','shippingCharged','targetMargin','salePrice','useOffsite','useCurrency','useSetup'].forEach(id=>$('#'+id).addEventListener('input',liveCalc));$('#useRecommendedBtn').onclick=()=>{$('#salePrice').value=calcProduct(collectProductDraft()).recommended.toFixed(2);liveCalc()};
$('#applyImageUrlBtn').onclick=()=>{draftImageData='';renderImagePreview($('#productImageUrl').value.trim())};$('#detectColorsBtn').onclick=detectProductColors;$('#tryAutoImageBtn').onclick=tryAutoImage;$('#productImageFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{draftImageData=await resizeImage(f);$('#productImageUrl').value='';renderImagePreview(draftImageData)}catch{alert('Das Bild konnte nicht verarbeitet werden.')}e.target.value=''};$('#removeImageBtn').onclick=()=>{draftImageData='';$('#productImageUrl').value='';renderImagePreview('')};
$('#productCategory').addEventListener('change',()=>{setCategoryOptions($('#productCategory').value,'');$('#productCategory').dataset.auto='';$('#productSubcategory').dataset.auto='';showCategorySuggestion(false)});$('#productSubcategory').addEventListener('change',()=>{$('#productCategory').dataset.auto='';$('#productSubcategory').dataset.auto='';showCategorySuggestion(false)});$('#productName').addEventListener('input',()=>showCategorySuggestion(true));$('#productNotes').addEventListener('input',()=>showCategorySuggestion(true));document.addEventListener('input',e=>{if(e.target.classList?.contains('supplier-url'))showCategorySuggestion(true)});
$$('.close-product-dialog,.cancel-product-dialog').forEach(b=>b.addEventListener('click',()=>$('#productDialog').close()));
$$('.close-batch-dialog,.cancel-batch-dialog').forEach(b=>b.addEventListener('click',()=>$('#batchDialog').close()));
$('#productForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const p=collectProductDraft();if(!p.name){$('#productName').focus();return}if(!p.pid){state.counters.product++;p.pid=displayId('PID',state.counters.product)}const i=state.products.findIndex(x=>x.key===p.key);if(i>=0)state.products[i]=p;else state.products.push(p);if(p.category&&p.subcategory)learnCategory(p);saveState();$('#productDialog').close()});
$('#deleteProductBtn').onclick=()=>{const key=$('#productKey').value;if(key&&confirm('Produkt wirklich löschen? Verknüpfungen in Batches bleiben als PID sichtbar, können aber nicht mehr kalkuliert werden.')){state.products=state.products.filter(p=>p.key!==key);saveState();$('#productDialog').close()}};
$('#addBatchItemBtn').onclick=()=>{const opts='<option value="">Produkt wählen …</option>'+state.products.map(p=>`<option value="${esc(p.pid)}">${esc(p.pid)} · ${esc(p.name)}</option>`).join('');$('#batchItemRows').insertAdjacentHTML('beforeend',`<div class="batch-item-row"><select class="batch-product">${opts}</select><input class="batch-qty" type="number" min="1" step="1" value="1"><div class="money batch-line-cost">0,00 €</div><button type="button" class="iconbtn remove-batch-item">✕</button></div>`);bindBatchItemEvents();liveBatchCalc()};['batchExtraCost','batchTargetMargin','batchSalePrice','batchUseOffsite','batchUseCurrency','batchUseSetup'].forEach(id=>$('#'+id).addEventListener('input',liveBatchCalc));$('#batchUseRecommendedBtn').onclick=()=>{$('#batchSalePrice').value=batchCalc(collectBatchDraft()).recommended.toFixed(2);liveBatchCalc()};
$('#batchForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const b=collectBatchDraft();b.items=sortBatchItemsByPid(b.items);if(!b.name){$('#batchName').focus();return}if(!b.bid){state.counters.batch++;b.bid=displayId('BID',state.counters.batch)}const i=state.batches.findIndex(x=>x.key===b.key);if(i>=0)state.batches[i]=b;else state.batches.push(b);saveState();$('#batchDialog').close()});$('#deleteBatchBtn').onclick=()=>{const key=$('#batchKey').value;if(key&&confirm('Batch wirklich löschen?')){state.batches=state.batches.filter(b=>b.key!==key);saveState();$('#batchDialog').close()}};
['listingFee','transactionPct','paymentPct','paymentFixed','offsitePct','currencyPct','feeVatPct','setupFee','setupSales'].forEach(k=>$('#'+k).addEventListener('input',e=>{state.settings[k]=num(e.target.value,defaultState.settings[k]);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderOverview();$('#setupPerSale').textContent=euro(state.settings.setupSales>0?state.settings.setupFee/state.settings.setupSales:0)}));
$('#productsCsvBtn').onclick=exportProductsCsv;$('#batchesCsvBtn').onclick=exportBatchesCsv;$('#exportBackupBtn').onclick=exportBackup;$('#dataBackupBtn').onclick=exportBackup;$('#importBackupBtn').onclick=()=>$('#backupFile').click();$('#dataImportBtn').onclick=()=>$('#backupFile').click();$('#backupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.products))throw Error();state={...structuredClone(defaultState),...x,settings:{...defaultState.settings,...x.settings},counters:{...defaultState.counters,...x.counters},categoryLearning:{...defaultState.categoryLearning,...x.categoryLearning}};migrateState(state);saveState();alert('Batchies-Backup wurde importiert.')}catch{alert('Ungültiges Batchies-Backup.')}e.target.value=''};

function jointFirstOrderForAllBatches(){
  const required=new Map();
  state.batches.forEach(b=>(b.items||[]).forEach(i=>required.set(i.pid,(required.get(i.pid)||0)+Math.max(1,num(i.qty,1)))));
  let totalCost=0,missingSupplier=false;const lines=[];
  [...required.entries()].sort((a,b)=>parseIdNumber(a[0],'PID')-parseIdNumber(b[0],'PID')||String(a[0]).localeCompare(String(b[0]),'de',{numeric:true})).forEach(([pid,needed])=>{
    const p=state.products.find(x=>x.pid===pid),s=simulationPreferredSupplier(p);
    if(!p||!s){missingSupplier=true;lines.push({pid,name:p?.name||'Produkt fehlt',needed,ordered:0,packs:0,cost:0,missing:true});return}
    const packQty=simulationPackageQty(s),packs=Math.max(1,Math.ceil(needed/packQty)),ordered=packQty*packs,cost=supplierOrderCost(s)*packs;
    totalCost+=cost;lines.push({pid,name:p.name,needed,ordered,packs,cost,missing:false});
  });
  return{lines,totalCost,missingSupplier}
}
function renderInvestments(){
  const body=$('#investmentsBody'),sumEl=$('#investmentsSum'),batchBody=$('#investmentBatchesBody'),batchSumEl=$('#batchOrdersSum'),grandEl=$('#investmentsGrandTotal');if(!body)return;
  state.investments=Array.isArray(state.investments)?state.investments:[];
  body.innerHTML=state.investments.length?state.investments.map(x=>{const href=safeUrl(x.url||'');return `<tr data-key="${esc(x.key)}"><td><input class="investment-type" value="${esc(x.type||'')}" placeholder="z. B. Gewerbeanmeldung, Drucker, Verpackung"></td><td><div class="investment-url-wrap"><input class="investment-url" type="url" value="${esc(x.url||'')}" placeholder="https://…" aria-label="URL der Investition" title="URL der Investition"><a class="iconbtn investment-open-url${href==='#'?' hidden':''}" href="${esc(href)}" target="_blank" rel="noopener noreferrer" title="URL öffnen">↗</a></div></td><td><input class="investment-cost" type="number" min="0" step="0.01" value="${num(x.cost)}"></td><td><button type="button" class="iconbtn investment-remove" title="Investition löschen">✕</button></td></tr>`}).join(''):`<tr><td colspan="4" class="muted">Noch keine Investitionen eingetragen.</td></tr>`;
  const invTotal=state.investments.reduce((a,x)=>a+num(x.cost),0);sumEl.textContent=euro(invTotal);
  const joint=jointFirstOrderForAllBatches();
  batchBody.innerHTML=joint.lines.length?joint.lines.map(x=>`<tr><td><span class="idchip">${esc(x.pid)}</span></td><td><div class="name">${esc(x.name)}</div></td><td>${x.needed} Stk.</td><td>${x.missing?'–':x.ordered+' Stk.'}${x.packs>1?` <span class="tiny">(${x.packs} Bestellungen)</span>`:''}</td><td class="money">${x.missing?'–':euro(x.cost)}</td></tr>`).join(''):`<tr><td colspan="5" class="muted">Noch keine Produkte in Batches vorhanden.</td></tr>`;
  batchSumEl.textContent=joint.missingSupplier?euro(joint.totalCost)+' + offen':euro(joint.totalCost);
  grandEl.textContent=joint.missingSupplier?euro(invTotal+joint.totalCost)+' + offen':euro(invTotal+joint.totalCost);
  $$('.investment-type,.investment-url,.investment-cost').forEach(el=>{el.oninput=()=>{const r=el.closest('tr'),x=state.investments.find(i=>i.key===r.dataset.key);if(!x)return;x.type=r.querySelector('.investment-type').value;x.url=r.querySelector('.investment-url').value.trim();x.cost=num(r.querySelector('.investment-cost').value);const open=r.querySelector('.investment-open-url'),href=safeUrl(x.url);if(open){open.href=href;open.classList.toggle('hidden',href==='#')}localStorage.setItem(STORAGE_KEY,JSON.stringify(state));const invTotal=state.investments.reduce((a,i)=>a+num(i.cost),0),joint=jointFirstOrderForAllBatches();$('#investmentsSum').textContent=euro(invTotal);$('#investmentsGrandTotal').textContent=joint.missingSupplier?euro(invTotal+joint.totalCost)+' + offen':euro(invTotal+joint.totalCost)}});
  $$('.investment-remove').forEach(b=>b.onclick=()=>{const key=b.closest('tr').dataset.key;state.investments=state.investments.filter(x=>x.key!==key);saveState()})
}

$('#addInvestmentBtn').onclick=()=>{state.investments.push({key:crypto.randomUUID(),type:'',url:'',cost:0});saveState()};const simulationReset=$('#simulationResetBtn');if(simulationReset)simulationReset.onclick=()=>{state.simulationSelectedBatches=[];localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderShoppingSimulation()};
renderAll();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
