function renderAll(){renderOverview();renderProducts();renderBatches();renderBatchSuggestions();renderSettings()}
function renderOverview(){const ps=state.products,cs=ps.map(calcProduct);$('#kpiProducts').textContent=ps.length;$('#kpiBatches').textContent=state.batches.length;$('#kpiReady').textContent=ps.filter(p=>p.status==='ready').length+' verkaufsbereit';$('#kpiAvgPrice').textContent=euro(ps.length?cs.reduce((a,c)=>a+c.recommended,0)/ps.length:0);$('#kpiAvgMargin').textContent=pct(ps.length?cs.reduce((a,c)=>a+c.margin,0)/ps.length:0);const s=state.settings;$('#feeRateSummary').textContent=(s.transactionPct+s.paymentPct).toFixed(2).replace('.',',')+' %';$('#feeFixedSummary').textContent=euro(s.listingFee+s.paymentFixed);$('#feeAdsSummary').textContent=s.offsitePct.toFixed(2).replace('.',',')+' %';$('#feeFxSummary').textContent=s.currencyPct.toFixed(2).replace('.',',')+' %';const el=$('#overviewProducts');if(!ps.length){el.innerHTML='<div class="empty"><strong>Noch keine Produkte</strong>Lege dein erstes Produkt an.<br><button class="btn primary" style="margin-top:10px" onclick="openProduct()">+ Produkt</button></div>';return}el.innerHTML='<div class="table-wrap"><table><thead><tr><th>ID</th><th>Produkt</th><th>Status</th><th>Kosten</th><th>VK</th><th>Marge</th></tr></thead><tbody>'+ps.slice(-6).reverse().map(p=>{const c=calcProduct(p);return `<tr style="cursor:pointer" onclick="openProduct('${p.key}')"><td><span class="idchip">${esc(p.pid)}</span></td><td><div class="name">${esc(p.name)}</div>${productColorDots(p.colors,true)}</td><td><span class="badge ${p.status}">${statusLabel(p.status)}</span></td><td class="money">${euro(c.costs)}</td><td class="money">${euro(p.salePrice)}</td><td>${pct(c.margin)}</td></tr>`}).join('')+'</tbody></table></div>'}
function renderSettings(){const s=state.settings;['listingFee','transactionPct','paymentPct','paymentFixed','offsitePct','currencyPct','feeVatPct','setupFee','setupSales'].forEach(k=>{const e=$('#'+k);if(e&&document.activeElement!==e)e.value=s[k]});$('#setupPerSale').textContent=euro(s.setupSales>0?s.setupFee/s.setupSales:0)}
$$('.tab').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.go)));function switchTab(t){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$$('.tabpage').forEach(p=>p.classList.add('hidden'));$('#tab-'+t).classList.remove('hidden')}
initColorFilter();$('#addProductBtn').onclick=()=>openProduct();$('#addBatchBtn').onclick=()=>openBatch();$('#searchProducts').oninput=renderProducts;$('#filterProductColor').onchange=renderProducts;$('#searchBatches').oninput=renderBatches;const refreshSuggestions=$('#refreshBatchSuggestionsBtn');if(refreshSuggestions)refreshSuggestions.onclick=renderBatchSuggestions;
$('#addSupplierBtn').onclick=()=>{const has=$$('.supplier-row').length;$('#supplierRows').insertAdjacentHTML('beforeend',supplierRowHtml({id:crypto.randomUUID(),name:'',url:'',priceType:'unit',price:0,minOrderQty:1,setPrice:0,setQty:1,totalShipping:0,imageUrl:'',preferred:!has}));bindSupplierEvents();liveCalc()};
$('#usePreferredPriceBtn').onclick=()=>{const s=preferredSupplier();if(s){$('#productBasePrice').value=supplierUnitPrice(s).toFixed(2);if(!$('#productImageUrl').value&&s.imageUrl){$('#productImageUrl').value=s.imageUrl;renderImagePreview(s.imageUrl)}liveCalc()}};
$('#addCostBtn').onclick=()=>{$('#costRows').insertAdjacentHTML('beforeend','<div class="cost-row"><input class="cost-name" placeholder="Kostenposition"><input class="cost-amount" type="number" min="0" step="0.01" value="0"><button type="button" class="iconbtn remove-cost">✕</button></div>');bindCostEvents();liveCalc()};
['productBasePrice','shippingCost','shippingCharged','targetMargin','salePrice','useOffsite','useCurrency','useSetup'].forEach(id=>$('#'+id).addEventListener('input',liveCalc));$('#useRecommendedBtn').onclick=()=>{$('#salePrice').value=calcProduct(collectProductDraft()).recommended.toFixed(2);liveCalc()};
$('#applyImageUrlBtn').onclick=()=>{draftImageData='';renderImagePreview($('#productImageUrl').value.trim())};$('#detectColorsBtn').onclick=detectProductColors;$('#tryAutoImageBtn').onclick=tryAutoImage;$('#productImageFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{draftImageData=await resizeImage(f);$('#productImageUrl').value='';renderImagePreview(draftImageData)}catch{alert('Das Bild konnte nicht verarbeitet werden.')}e.target.value=''};$('#removeImageBtn').onclick=()=>{draftImageData='';$('#productImageUrl').value='';renderImagePreview('')};
$('#productCategory').addEventListener('change',()=>{setCategoryOptions($('#productCategory').value,'');$('#productCategory').dataset.auto='';$('#productSubcategory').dataset.auto='';showCategorySuggestion(false)});$('#productSubcategory').addEventListener('change',()=>{$('#productCategory').dataset.auto='';$('#productSubcategory').dataset.auto='';showCategorySuggestion(false)});$('#productName').addEventListener('input',()=>showCategorySuggestion(true));$('#productNotes').addEventListener('input',()=>showCategorySuggestion(true));document.addEventListener('input',e=>{if(e.target.classList?.contains('supplier-url'))showCategorySuggestion(true)});
$$('.close-product-dialog,.cancel-product-dialog').forEach(b=>b.addEventListener('click',()=>$('#productDialog').close()));
$$('.close-batch-dialog,.cancel-batch-dialog').forEach(b=>b.addEventListener('click',()=>$('#batchDialog').close()));
$('#productForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const p=collectProductDraft();if(!p.name){$('#productName').focus();return}if(!p.pid){state.counters.product++;p.pid=displayId('PID',state.counters.product)}const i=state.products.findIndex(x=>x.key===p.key);if(i>=0)state.products[i]=p;else state.products.push(p);if(p.category&&p.subcategory)learnCategory(p);saveState();$('#productDialog').close()});
$('#deleteProductBtn').onclick=()=>{const key=$('#productKey').value;if(key&&confirm('Produkt wirklich löschen? Verknüpfungen in Batches bleiben als PID sichtbar, können aber nicht mehr kalkuliert werden.')){state.products=state.products.filter(p=>p.key!==key);saveState();$('#productDialog').close()}};
$('#addBatchItemBtn').onclick=()=>{const opts='<option value="">Produkt wählen …</option>'+state.products.map(p=>`<option value="${esc(p.pid)}">${esc(p.pid)} · ${esc(p.name)}</option>`).join('');$('#batchItemRows').insertAdjacentHTML('beforeend',`<div class="batch-item-row"><select class="batch-product">${opts}</select><input class="batch-qty" type="number" min="1" step="1" value="1"><div class="money batch-line-cost">0,00 €</div><button type="button" class="iconbtn remove-batch-item">✕</button></div>`);bindBatchItemEvents();liveBatchCalc()};['batchExtraCost','batchTargetMargin','batchSalePrice','batchUseOffsite','batchUseCurrency','batchUseSetup'].forEach(id=>$('#'+id).addEventListener('input',liveBatchCalc));$('#batchUseRecommendedBtn').onclick=()=>{$('#batchSalePrice').value=batchCalc(collectBatchDraft()).recommended.toFixed(2);liveBatchCalc()};
$('#batchForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const b=collectBatchDraft();b.items=sortBatchItemsByPid(b.items);if(!b.name){$('#batchName').focus();return}if(!b.bid){state.counters.batch++;b.bid=displayId('BID',state.counters.batch)}const i=state.batches.findIndex(x=>x.key===b.key);if(i>=0)state.batches[i]=b;else state.batches.push(b);saveState();$('#batchDialog').close()});$('#deleteBatchBtn').onclick=()=>{const key=$('#batchKey').value;if(key&&confirm('Batch wirklich löschen?')){state.batches=state.batches.filter(b=>b.key!==key);saveState();$('#batchDialog').close()}};
['listingFee','transactionPct','paymentPct','paymentFixed','offsitePct','currencyPct','feeVatPct','setupFee','setupSales'].forEach(k=>$('#'+k).addEventListener('input',e=>{state.settings[k]=num(e.target.value,defaultState.settings[k]);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));renderOverview();$('#setupPerSale').textContent=euro(state.settings.setupSales>0?state.settings.setupFee/state.settings.setupSales:0)}));
$('#productsCsvBtn').onclick=exportProductsCsv;$('#batchesCsvBtn').onclick=exportBatchesCsv;$('#exportBackupBtn').onclick=exportBackup;$('#dataBackupBtn').onclick=exportBackup;$('#importBackupBtn').onclick=()=>$('#backupFile').click();$('#dataImportBtn').onclick=()=>$('#backupFile').click();$('#backupFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.products))throw Error();state={...structuredClone(defaultState),...x,settings:{...defaultState.settings,...x.settings},counters:{...defaultState.counters,...x.counters},categoryLearning:{...defaultState.categoryLearning,...x.categoryLearning}};migrateState(state);saveState();alert('Batchies-Backup wurde importiert.')}catch{alert('Ungültiges Batchies-Backup.')}e.target.value=''};
renderAll();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
