
function batchProductionPlan(b){
  const grouped=new Map();
  (b.items||[]).forEach(i=>{if(!i.pid)return;grouped.set(i.pid,(grouped.get(i.pid)||0)+Math.max(1,num(i.qty,1)))});
  const lines=[];let firstOrderCost=0,possible=Infinity,missing=false,limiter=[];
  grouped.forEach((qty,pid)=>{const p=state.products.find(x=>x.pid===pid);if(!p)return;const sup=(p.suppliers||[]).find(x=>x.preferred)||(p.suppliers||[])[0];if(!sup){missing=true;lines.push({pid,name:p.name,qty,available:0,orderCost:0,batches:0,missing:true});possible=0;return}const available=sup.priceType==='set'?Math.max(1,num(sup.setQty,1)):Math.max(1,num(sup.minOrderQty,1));const orderCost=supplierOrderCost(sup);const batches=Math.floor(available/qty);firstOrderCost+=orderCost;possible=Math.min(possible,batches);lines.push({pid,name:p.name,qty,available,orderCost,batches,missing:false})});
  if(possible===Infinity)possible=0;
  limiter=lines.filter(x=>x.batches===possible&&!x.missing);
  const extrasForPossible=num(b.extraCost)*possible;
  return{lines,firstOrderCost,possible,limiter,extrasForPossible,totalInvestment:firstOrderCost+extrasForPossible,unitBatchCost:batchCalc(b).total,missing};
}
function renderBatchProductionPlan(b){const el=$('#batchProductionContent');if(!el)return;const p=batchProductionPlan(b);if(!p.lines.length){el.innerHTML='<div class="assistant-empty" style="margin-top:10px">Füge Produkte hinzu, um die Herstellungsplanung zu berechnen.</div>';return}const limiter=p.limiter.length?p.limiter.map(x=>esc(x.pid+' · '+x.name)).join(', '):(p.missing?'Lieferantendaten fehlen':'–');el.innerHTML=`<div class="production-kpis"><div class="production-kpi"><div class="label">Erste Warenbestellung</div><div class="value">${euro(p.firstOrderCost)}</div></div><div class="production-kpi"><div class="label">Mögliche vollständige Batches</div><div class="value">${p.possible}</div></div><div class="production-kpi"><div class="label">Engpass</div><div class="value" style="font-size:12px">${limiter}</div></div><div class="production-kpi"><div class="label">Material-EK pro Batch</div><div class="value">${euro(p.unitBatchCost)}</div></div></div><div class="tiny" style="margin-top:7px">Erste Warenbestellung = je Produkt eine MOQ bzw. ein Set inkl. hinterlegtem Lieferantenversand. Batch-Zusatzkosten werden separat pro herstellbarem Batch gerechnet.${p.possible?` Für ${p.possible} Batches wären das zusätzlich ${euro(p.extrasForPossible)}; Gesamtinvestition ${euro(p.totalInvestment)}.`:''}${p.missing?' Für mindestens ein Produkt fehlen Lieferantendaten; die mögliche Batch-Anzahl kann deshalb 0 sein.':''}</div><div class="production-lines"><div class="production-line head"><span>Produkt</span><span>Bedarf/Batch</span><span>1. Bestellung</span><span>Reicht für</span></div>${p.lines.map(x=>`<div class="production-line"><span><b>${esc(x.pid)}</b> · ${esc(x.name)}</span><span>${x.qty} Stk.</span><span>${x.missing?'–':x.available+' Stk. · '+euro(x.orderCost)}</span><span>${x.missing?'–':x.batches+' Batches'}</span></div>`).join('')}</div>`}
function renderBatches(){state.batches.forEach(b=>{b.items=sortBatchItemsByPid(b.items)});const q=($('#searchBatches')?.value||'').toLowerCase().trim(),bs=state.batches.filter(b=>(b.bid+' '+b.name+' '+(b.notes||'')).toLowerCase().includes(q)),el=$('#batchesTable');if(!bs.length){el.innerHTML='<div class="empty"><strong>'+(state.batches.length?'Keine Treffer':'Noch keine Batches')+'</strong>Ein Batch kann mehrere Produkt-PIDs enthalten.</div>';return}el.innerHTML='<div class="table-wrap"><table><thead><tr><th>ID</th><th>Batch</th><th>Status</th><th>Produkte</th><th>EK gesamt</th><th>Empf. VK</th><th>VK</th><th>Marge</th><th></th></tr></thead><tbody>'+bs.map(b=>{const c=batchCalc(b);return `<tr><td><span class="idchip">${esc(b.bid)}</span></td><td><div class="name">${esc(b.name)}</div></td><td><span class="badge ${b.status}">${statusLabel(b.status)}</span></td><td>${(b.items||[]).map(i=>esc(i.pid)+' × '+num(i.qty,1)).join(', ')||'–'}</td><td class="money">${euro(c.total)}</td><td class="money positive">${euro(c.recommended)}</td><td class="money">${euro(b.salePrice)}</td><td class="${c.margin>=num(b.targetMargin,30)?'positive':'negative'}">${pct(c.margin)}</td><td><button class="iconbtn" onclick="openBatch('${b.key}')">✎</button></td></tr>`}).join('')+'</tbody></table></div>'}
function renderBatchItemRows(items){items=sortBatchItemsByPid(items);const opts='<option value="">Produkt wählen …</option>'+state.products.map(p=>`<option value="${esc(p.pid)}">${esc(p.pid)} · ${esc(p.name)}</option>`).join('');$('#batchItemRows').innerHTML=(items.length?items:[{pid:'',qty:1}]).map(i=>`<div class="batch-item-row"><select class="batch-product">${opts}</select><input class="batch-qty" type="number" min="1" step="1" value="${Math.max(1,num(i.qty,1))}"><div class="money batch-line-cost">0,00 €</div><button type="button" class="iconbtn remove-batch-item">✕</button></div>`).join('');$$('.batch-item-row').forEach((r,idx)=>{r.querySelector('.batch-product').value=items[idx]?.pid||''});bindBatchItemEvents();liveBatchCalc()}
function bindBatchItemEvents(){$$('.batch-product,.batch-qty').forEach(e=>e.addEventListener('input',liveBatchCalc));$$('.remove-batch-item').forEach(b=>b.addEventListener('click',()=>{b.closest('.batch-item-row').remove();liveBatchCalc()}))}
function sortBatchItemsByPid(items){return [...(items||[])].sort((a,b)=>parseIdNumber(a.pid,'PID')-parseIdNumber(b.pid,'PID')||String(a.pid).localeCompare(String(b.pid),'de',{numeric:true}))}
function collectBatchDraft(){return{key:$('#batchKey').value||crypto.randomUUID(),bid:$('#batchBid').value,name:$('#batchName').value.trim(),status:$('#batchStatus').value,items:$$('.batch-item-row').map(r=>({pid:r.querySelector('.batch-product').value,qty:Math.max(1,num(r.querySelector('.batch-qty').value,1))})).filter(i=>i.pid),extraCost:num($('#batchExtraCost').value),targetMargin:num($('#batchTargetMargin').value,30),salePrice:num($('#batchSalePrice').value),useOffsite:$('#batchUseOffsite').checked,useCurrency:$('#batchUseCurrency').checked,useSetup:$('#batchUseSetup').checked,notes:$('#batchNotes').value.trim()}}
function liveBatchCalc(){const b=collectBatchDraft(),c=batchCalc(b);$$('.batch-item-row').forEach(r=>{const p=state.products.find(x=>x.pid===r.querySelector('.batch-product').value),q=Math.max(1,num(r.querySelector('.batch-qty').value,1));r.querySelector('.batch-line-cost').textContent=euro(p?productPurchaseCost(p)*q:0)});$('#batchProductsCost').textContent=euro(c.productCost);$('#batchExtraCostLive').textContent=euro(c.extra);$('#batchTotalCost').textContent=euro(c.total);$('#batchFeesLive').textContent=euro(c.fees);$('#batchProfitLive').textContent=euro(c.profit);$('#batchMarginLive').textContent=pct(c.margin);$('#batchRecommended').textContent=euro(c.recommended);renderBatchProductionPlan(b);if($('#batchKey').value&&typeof renderBatchAssistant==='function')renderBatchAssistant(b)}
function openBatch(key=null){const b=key?state.batches.find(x=>x.key===key):null;$('#batchKey').value=b?.key||'';$('#batchBid').value=b?.bid||'';$('#batchBidLabel').textContent=b?.bid||'BID wird beim Speichern vergeben';$('#batchModalTitle').textContent=b?'Batch bearbeiten':'Neuer Batch';$('#batchName').value=b?.name||'';$('#batchStatus').value=b?.status||'idea';renderBatchItemRows(b?.items||[]);$('#batchExtraCost').value=b?.extraCost??0;$('#batchTargetMargin').value=b?.targetMargin??30;$('#batchSalePrice').value=b?.salePrice??0;$('#batchUseOffsite').checked=!!b?.useOffsite;$('#batchUseCurrency').checked=!!b?.useCurrency;$('#batchUseSetup').checked=!!b?.useSetup;$('#batchNotes').value=b?.notes||'';$('#deleteBatchBtn').classList.toggle('hidden',!b);liveBatchCalc();$('#batchDialog').showModal();if(b&&typeof renderBatchAssistant==='function')renderBatchAssistant(b)}
window.openBatch=openBatch;
